# Generated by Django 4.2.26 on 2025-11-18 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id_author', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('country', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id_genre', models.AutoField(primary_key=True, serialize=False)),
                ('name_genre', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_join', models.DateField()),
                ('favourite_id_author', models.ForeignKey(db_column='favourite_id_author', on_delete=django.db.models.deletion.CASCADE, to='main.author')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id_book', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('year', models.IntegerField()),
                ('file_path', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('age_rating', models.CharField(max_length=10)),
                ('id_author', models.ForeignKey(db_column='id_author', on_delete=django.db.models.deletion.CASCADE, to='main.author')),
                ('id_genre', models.ForeignKey(db_column='id_genre', on_delete=django.db.models.deletion.CASCADE, to='main.genre')),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
