# Generated by Django 4.2.26 on 2025-11-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_author_photo_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
